#! /bin/bash

# Compiles notes in a separate directory.

SIL=${SILENCE-no} # compile files quietly

DIR=${DIRECTORY-${HOME}/umea_spring_2017_notes} # directory of compilation
NAM=${FILENAME-umea_spring_2017_notes} # name of the .pdf file

while read cmd; do
	if [ "$SIL" = "yes" ]; then
                echo "$cmd ..."
		$cmd &> /dev/null
	else
		$cmd
	fi
done <<EOF
pdflatex main
pdflatex main
bibtex main
pdflatex main
pdflatex main
EOF

mkdir -p $DIR
mkdir -p ${DIR}/aux # directory of auxiliary files

mv `ls -d ${PWD}/main.* | grep -Ev '.tex|.pdf'` ${DIR}/aux # auxiliary files
mv main.pdf ${DIR}/${NAM}.pdf # pdf file

